# Generated by ChatGPT :)

from flask import Flask, Response
from picamera2 import Picamera2
import cv2


app = Flask(__name__)

# Ініціалізація камери Raspberry Pi
camera = Picamera2()
camera_config = camera.create_video_configuration(main={"size": (1920, 1080)})
camera.configure(camera_config)
camera.start()

def generate_frames():
    while True:
        # Отримання кадру з камери
        frame = camera.capture_array()
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
        
        # Кодування кадру у формат JPEG зі стисненням
        encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 50]  # Якість JPEG: 50%
        _, buffer = cv2.imencode('.jpg', frame, encode_param)
        frame = buffer.tobytes()

        # Повернення кадру у потоці
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/video_feed')
def video_feed():
    """Повертає потік відео у форматі MJPEG."""
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5008)
